        .text
        .globl  lambda_wrapper
        .type   lambda_wrapper, @function
lambda_wrapper:
.LFB0:
        .cfi_startproc
        pushq   %rbp
        .cfi_def_cfa_offset 16
        .cfi_offset 6, -16
        movq    %rsp, %rbp
        .cfi_def_cfa_register 6
        call    lambda_wrapper_impl
        nop
        popq    %rbp
        .cfi_def_cfa 7, 8
        ret
        .cfi_endproc
.LFE0:
        .size   lambda_wrapper, .-lambda_wrapper
